### ISSUE TITLE
When using a persistent volume, pass the size argument to the flex driver options

### ISSUE THREAD

**Issue by rgolangh** [rgolangh/ovirt-flexdriver#4]
A persistent volume has `storage: capacity` attribute as part of its definition, but nothing from this is being passed to the Attach call-out. To over come this one must specify the `Size` in the flex driver options.

Example persistent volume definition:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  flexVolume:
    driver: ovirt/ovirt-flexdriver
    fsType: "ext4"
    readOnly: true
    options:
      Size: 1Gi
      ovirtStorageDomain: data1
```
